lst= [u'Meter_serial', u'SumTotalCam', u'NameOfMeter', u'total_recharges',
       u'total_consumption', u'calculated_wallet_bal', u'actual_wallet_bal',
       u'LastDataPointTime', u'sumSuccessRecharge', u'sumProcessingRecharge',
       u'ScriptTime', u'monthlyConsumptionTime', u'Associate_date',
       u'Monthly_consumption_api_status', u'Consumed_rupees_negative',
       u'start_time_negative_card', u'last_time_negative_card',
       u'current_month_disabledualsourcescreen',
       u'current_month_eb_consumption', u'current_month_dg_consumption',
       u'current_month_overallEB_DGconsumption',
       u'current_month_totalmonthlyconsumption',
       u'all_month_total_eb_dg_consumption', u'all_month_eb_consumption',
       u'all_month_dg_consumption', u'meter_address_SHI', u'sc_no',
       u'supply_type', u'grid_id', u'user_mobile_number',
       u'associate_initiated_date', u'associate_date', u'meter_address_UMD',
       u'username', u'email', u'last data point time', u'date_of_associate',
       u'date_of_deassociate', u'total_Success_recharge',
       u'total_Processing_recharge', u'ldp_time', u'ldp_credit_remain',
       u'is_Supply_generator', u'active_energy_at_ldp', u'active_energy_diff',
       u'tariff_update_time', u'db_tariff', u'eb_tariff', u'time_before',
       u'credit_energy_before', u'active_energy_before', u'sum_success_before',
       u'sum_processing_before', u'settlement_success',
       u'settlement_processing', u'cam-deduction-amount', u'cam-started-at',
       u'cam-updated-at', u'total-cam-charges', u'cam_success',
       u'cam_processing', u'wallet_match', u'tr_sum_of_recharge_amount',
       u'diff_wallet', u'tariff_1s_ruppee', u'Assigned_meter_filteration',
       u'IP_mismtach', u'diff_wallet_need_to_check', u'CONSUMED_RUPP',
       u'CON_kwh', u'EXP_TARIFF', u'MATCH_TARIFF', u'diff_exp_and_Act_tar',
       u'diff_exp_and_Act_tar.1', u'macth_cam_with_cam_recharges',
       u'cam_recharges_toal_sum', u'diff_TOTAL_CAM_RECH_AND_CAM_DEDUT',
       u'macth_cam_expected_and_cam_recharges',
       u'DIFF_OF_EXPECTED_AND_ACTUAL_CAM', u'has_error'];


for index, x in enumerate(lst):
       print index, x